# Generated by Django 5.1 on 2024-10-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_certificates_delete_about_delete_homecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skills/'),
        ),
    ]
